config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/webhooks/stripe' 

  devise_for :users

  resources  :charges
  resources  :products
  resource   :subscription
  
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user

  def receipt
    Receipts::Receipt.new(
      id: id,
      product:"Store",
      company: {
        name:     "Dragonicity Ltd",
        address:  "17/F, 248 Des Voeux Road, Central, Hong Kong",
        email:    "admin@dragonicity.com",
        logo:     Rails.root.join("app/assets/images/dragonicity-logo-english.jpg")
      },
      line_items: [
        ["Date",          created_at.to_s],
        ["Acount Billed", user.email],
        ["Product",       "Monthly subscription"],
        ["Currency",      stripe_currency],
        ["Amount",        amount / 100],
        ["Card Charged",  "#{card_brand} (**** **** **** #{card_last4})"]
      ]
    )
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :charges

  def stripe_customer
    if stripe_id?
      Stripe::Customer.retrieve(stripe_id)
    else
      stripe_customer = Stripe::Customer.create(email: email)
      update(stripe_id: stripe_customer.id)
      stripe_customer
    end
  end

  def subscribed?
    # Check for subscribed and free trial 
    stripe_subscription_id? || (expires_at? && Time.zone.now < expires_at)
  end
end

app/models/webhooks/charge_succeeded.rb
module Webhooks
  class ChargeSucceeded
    def call(event)
      charge = event.data.object

      user = User.find_by(stripe_id: charge.customer)

      # Avoid creating duplicates if it exists due to webhook process

      c = user.charges.where(stripe_id: charge.id).first_or_create
      
      c.update(
        stripe_currency: charge.currency,
        amount:          charge.amount,
        card_brand:      charge.source.brand,
        card_last4:      charge.source.last4,
        card_exp_month:  charge.source.exp_month,
        card_exp_year:   charge.source.exp_year
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_charge

  def show
    respond_to do |format|
      format.pdf { send_data(@charge.receipt.render,
                             filename: "#{@charge.id}-store-receipt.pdf",
                             type: "application/pdf",
                             disposition: :inline
                             )
    }
    end
  end

  private

    def set_charge
      @charge = current_user.charges.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :secret)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  end

  def create
    customer = current_user.stripe_customer

    begin
      subscription = customer.subscriptions.create(
        source: params[:stripeToken],
        plan:   params[:plan]
      )

      current_user.assign_attributes(
        stripe_subscription_id: subscription.id,
        expires_at: nil
      )
      
      current_user.assign_attributes(
        card_brand:     params[:user][:card_brand],
        card_last4:     params[:user][:card_last4],
        card_exp_month: params[:user][:card_exp_month],
        card_exp_year:  params[:user][:card_exp_year]
      ) if params[:user][:card_last4]

      current_user.save

      flash.notice = "Thanks for subscribing"
      redirect_to root_path
    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
    end
  end

  def show
  end

  def update
    customer = current_user.stripe_customer

    begin
      source = customer.sources.create(source: params[:stripeToken])

      customer.default_source = source.id
      customer.save

      current_user.assign_attributes(
        card_brand:     params[:user][:card_brand],
        card_last4:     params[:user][:card_last4],
        card_exp_month: params[:user][:card_exp_month],
        card_exp_year:  params[:user][:card_exp_year]
      )

      current_user.save

      flash.notice = "Your card was updated successfully"
      redirect_to root_path
    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :show
    end
  end

  def destroy
    customer = current_user.stripe_customer

    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete

    expires_at = Time.zone.at(subscription.current_period_end)
    current_user.update(expires_at: expires_at, stripe_subscription_id: nil)

    redirect_to root_path, notice: "You have cancelled your subscription. You will have access until #{current_user.expires_at.to_date}."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.erb
<div class="container"> 
  <div class="row">
    <div class="col-md-12 no-padding">
      <% flash.each do |key, msg| %>
        <div class="alert alert-<%= key %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= msg %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <li><%= link_to "Products", products_path, class: "nav-link" %></li>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Account", edit_user_registration_path, class: "mr-2" %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, class: "mr-2" %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/','data-turbolinks-track': 'reload' %>

    <%= tag :meta, name: "stripe_publishable_key", content: Rails.application.secrets.PUBLISHABLE_KEY %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :secret %>
    <%= form.text_area :secret, id: :product_secret %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.secret %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<% if user_signed_in? && current_user.subscribed? %>
  <p>
    <strong>Secret:</strong>
    <%= @product.secret %>
  </p>
<% else %>
  <%= link_to 'Subscribe', new_subscription_path(plan: "mentor-individual"), class: "btn btn=primary" %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/subscriptions/new.html.erb
<h1>Subscribe</h1>

<% if current_user.card_last4? %>
  <%= form_with url: subscription_path, id: "existing-card", local: true do %>
    <p> Pay with existing card:</p>
    <div><strong>Card on file: </strong> <%= current_user.card_brand %> (**** **** **** <%= current_user.card_last4 %>)</div>
    <div><strong>Expiration: </strong> <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %>)</div>
    <p>or <%= link_to "Add a new card", "#", class: "show-card-form" %></p>
 
    <%= hidden_field_tag :plan, params[:plan] %>

  <% end %>
<% end %>

<%= form_with url: subscription_path, id: "payment-form", style: (current_user.card_last4? ? "display:none" : nil), local: true do |form| %>
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <%= hidden_field_tag :plan, params[:plan] %>

  <input type="submit" class="submit" value="Submit Payment">
<% end %>

app/views/subscriptions/show.html.erb
<h1>Update your card</h1>

<%= form_tag subscription_path, method: :put, id: "payment-form" do %>
 <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Change card details</button>

<% end %>